[project]
name = "ri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.sources]
trie = { workspace = true }

[tool.uv.workspace]
members = ["packages/*", "Lab4"]
