from typing import Iterator

class BPlusTree[K, V]:
    def __init__(self): ...
    def __iter__(self) -> Iterator[tuple[K, V]]: ...
    def insert(self, key: K, value: V): ...
    def find(self, key: K) -> V | None: ...
