[project]
name = "trie"
version = "0.1.0"
description = "BAsic Trie data structure"
readme = "README.md"
authors = [{ name = "Dumitru Mițca", email = "dumitru0mitca@gmail.com" }]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
