[project]
name = "indexing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Dumitru Mițca", email = "dumitru0mitca@gmail.com" }]
requires-python = ">=3.13"
dependencies = ["trie", "stemmer", "bplustree"]

[tool.uv.sources]
bplustree = { workspace = true }
trie = { workspace = true }
stemmer = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
