services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongo:
        condition: service_healthy

  url-frontier:
    build:
      context: ..
      dockerfile: ./Proiect/url_frontier/Dockerfile
    ports:
      - 8000:8080
    environment:
      URL_FRONTIER_MONGODB_CONNECTION: mongodb://root:example@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

  crawler:
    build:
      context: ..
      dockerfile: ./Proiect/crawler/Dockerfile
    deploy:
      mode: replicated
      replicas: 16
      restart_policy:
        condition: on-failure
        max_attempts: 10
    environment:
      CRAWLER_URL_FRONTIER_CONNECTION: "http://url-frontier:8080"
      CRAWLER_MONGODB_CONNECTION: mongodb://root:example@mongo:27017/
    volumes:
      - ./docker-volume/sites:/app/Proiect/crawler/sites
    depends_on:
      mongo:
        condition: service_healthy
      url-frontier:
        condition: service_started

  indexer:
    build:
      context: ..
      dockerfile: ./Proiect/indexerd/Dockerfile
    volumes:
      - ./docker-volume/data:/app/Proiect/indexerd/data
      - ./docker-volume/sites:/app/Proiect/indexerd/sites
      - ./docker-volume/indexes:/app/Proiect/indexerd/indexes

  web-search:
    build:
      context: ..
      dockerfile: ./Proiect/web-search/Dockerfile
    ports:
      - 8080:5000
    volumes:
      - ./docker-volume/indexes:/app/Proiect/web-search/indexes
      - ./docker-volume/data:/app/Proiect/web-search/data
