USER_AGENT: str = ...

class RobotsTxt:
    @staticmethod
    def from_contents(robotstxt: str) -> RobotsTxt: ...
    @staticmethod
    def deserialize(serialized: str) -> RobotsTxt: ...
    def serialize(self) -> str: ...
    def is_allowed(self, url: str) -> bool: ...
    def crawl_delay(self) -> int | None: ...
