[project]
name = "lab5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["trie", "stemmer", "bplustree"]

[tool.uv.sources]
bplustree = { workspace = true }
trie = { workspace = true }
stemmer = { workspace = true }
