[project]
name = "lab7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "indexing",
    "searchfuncs",
]

[tool.uv.sources]
indexing = { workspace = true }
searchfuncs = { workspace = true }
